-- Step 1:
ALTER TABLE STUDENTS RENAME COLUMN ST_ID TO STUDENT_ID;

-- Step 2:
ALTER TABLE STUDENTS ALTER COLUMN ST_NAME TYPE VARCHAR(30);
ALTER TABLE STUDENTS ALTER COLUMN ST_LAST TYPE VARCHAR(30);

-- Step 3:
CREATE TABLE TEMP_INTERESTS (
    STUDENT_ID INTEGER REFERENCES STUDENTS(STUDENT_ID),
    INTERESTS VARCHAR[]
);

-- Step 4:
INSERT INTO TEMP_INTERESTS (STUDENT_ID, INTERESTS)
SELECT STUDENT_ID, ARRAY_AGG(INTEREST) 
FROM INTERESTS 
GROUP BY STUDENT_ID;

-- Step 5:
DROP TABLE INTERESTS;
ALTER TABLE TEMP_INTERESTS RENAME TO INTERESTS;
