-- Step 1: Rename the STUDENTS.ST_ID to STUDENTS.STUDENT_ID
ALTER TABLE STUDENTS RENAME COLUMN ST_ID TO STUDENT_ID;

-- Step 2: Change the length of STUDENTS.ST_NAME and STUDENTS.ST_LAST from 20 to 30
ALTER TABLE STUDENTS ALTER COLUMN ST_NAME TYPE VARCHAR(30);
ALTER TABLE STUDENTS ALTER COLUMN ST_LAST TYPE VARCHAR(30);

-- Step 3: Create a new table to convert INTEREST to an array of strings
CREATE TABLE TEMP_INTERESTS (
    STUDENT_ID INTEGER REFERENCES STUDENTS(STUDENT_ID),
    INTERESTS VARCHAR[]
);

-- Step 4: Insert data into TEMP_INTERESTS with interests aggregated into an array
INSERT INTO TEMP_INTERESTS (STUDENT_ID, INTERESTS)
SELECT STUDENT_ID, ARRAY_AGG(INTEREST) 
FROM INTERESTS 
GROUP BY STUDENT_ID;

-- Step 5: Drop the old INTERESTS table and rename TEMP_INTERESTS to INTERESTS
DROP TABLE INTERESTS;
ALTER TABLE TEMP_INTERESTS RENAME TO INTERESTS;
