-- Step 1:
CREATE TABLE ORIGINAL_INTERESTS (
    STUDENT_ID INTEGER REFERENCES STUDENTS(STUDENT_ID),
    INTEREST VARCHAR(20)
);

-- Step 2:
INSERT INTO ORIGINAL_INTERESTS (STUDENT_ID, INTEREST)
SELECT STUDENT_ID, UNNEST(INTERESTS) 
FROM INTERESTS;

-- Step 3: 
DROP TABLE INTERESTS;
ALTER TABLE ORIGINAL_INTERESTS RENAME TO INTERESTS;

-- Step 4:
ALTER TABLE STUDENTS RENAME COLUMN STUDENT_ID TO ST_ID;
ALTER TABLE STUDENTS ALTER COLUMN ST_NAME TYPE VARCHAR(20);
ALTER TABLE STUDENTS ALTER COLUMN ST_LAST TYPE VARCHAR(20);
